// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhi584H3G1s1QvDIeZ50BNeY4b5fo52-Q',
    appId: '1:884518574077:web:3c1d38882bfd2a8c2cab94',
    messagingSenderId: '884518574077',
    projectId: 'food-delivery-62453',
    authDomain: 'food-delivery-62453.firebaseapp.com',
    storageBucket: 'food-delivery-62453.appspot.com',
    measurementId: 'G-56WTBV4G5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWwMc-9ALe1W8F1ztkGU9cMvl9eQ-D7Rw',
    appId: '1:884518574077:android:51689779909588c52cab94',
    messagingSenderId: '884518574077',
    projectId: 'food-delivery-62453',
    storageBucket: 'food-delivery-62453.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpQfLfyoEbplyyBgeOPU9JCridt174jo8',
    appId: '1:884518574077:ios:80b1cb2b953ed6b32cab94',
    messagingSenderId: '884518574077',
    projectId: 'food-delivery-62453',
    storageBucket: 'food-delivery-62453.appspot.com',
    iosBundleId: 'com.example.foodApp',
  );
}
